name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # - run: pm2 stop portfolio-client
      # - run: pm2 delete portfolio-client

      - run: npm i
        working-directory: client

      - run: npm run build
        working-directory: client
        env:
          CI: false

      - run: pm2 start npm --name "portfolio-client" -- run serve --spa
        working-directory: client

      - run: |
          pm2 stop portfolio-client
          pm2 start portfolio-client
          pm2 save
          pm2 resurrect
          sudo service nginx restart
