name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: pm2 delete portfolio_client
      - run: pm2 delete portfolio_server

      - run: npm i
        working-directory: client

      - run: npm run build
        working-directory: client
        env:
          CI: false

      - run: pm2 start npm --name "portfolio_client" -- run serve --spa
        working-directory: client

      - run: |
          cd server
          touch .env
          echo NODE_ENV='${{ secrets.NODE_ENV }}' >> .env
          echo PROD_DB_USERNAME='${{ secrets.PROD_DB_USERNAME }}' >> .env
          echo PROD_DB_PW='${{ secrets.PROD_DB_PW }}' >> .env
          echo PROD_DB_PORT='${{ secrets.PROD_DB_PORT }}' >> .env
          echo PROD_DB_HOST='${{ secrets.PROD_DB_HOST }}' >> .env
          echo PROD_DB_NAME='${{ secrets.PROD_DB_NAME }}' >> .env
          echo PORT='${{ secrets.PORT }}' >> .env

      - run: npm i
        working-directory: server

      - run: pm2 start npm --name "portfolio_server" -- run start-prod
        working-directory: server

      - run: |
          pm2 stop portfolio_client
          pm2 start portfolio_client
          pm2 stop portfolio_server
          pm2 start portfolio_server
          pm2 save
          pm2 resurrect
          sudo service nginx restart
